# Generated by Django 4.0.5 on 2023-01-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password_hash', models.TextField()),
                ('access_token', models.TextField(null=True)),
                ('game_role', models.TextField(null=True)),
                ('currently_playing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_index', models.IntegerField()),
                ('turn_index', models.IntegerField(null=True)),
                ('game_joined_timestamp', models.DateTimeField(auto_now_add=True)),
                ('index_won', models.IntegerField(null=True)),
                ('index_left', models.IntegerField(null=True)),
                ('colour', models.TextField()),
                ('level_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_id', models.IntegerField()),
                ('player', models.IntegerField()),
                ('token', models.IntegerField(null=True)),
                ('dice_result', models.IntegerField(null=True)),
                ('action', models.TextField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_join_index', models.IntegerField(null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('is_first', models.BooleanField(default=False)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level')),
                ('log_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gamelog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gamelog',
            constraint=models.UniqueConstraint(fields=('game', 'instruction_id'), name='game instruction_id pk'),
        ),
    ]
