# Generated by Django 4.0.5 on 2022-12-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
