# Generated by Django 4.0.5 on 2022-09-13 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='colour',
        ),
    ]
