# Generated by Django 4.0.5 on 2023-01-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('user_1', models.ForeignKey(null=True,
                                             on_delete=django.db.models.deletion.SET_NULL,
                                             to='api.user')),
                ('user_2', models.ForeignKey(null=True,
                                             on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='%(class)s_requests_created',
                                             to='api.user')),
            ],
        ),
    ]
