# Generated by Django 4.0.5 on 2022-09-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_remove_portfolio_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True,
                                               on_delete=django.db.models.deletion.CASCADE,
                                               to='api.location')),
                ('value', models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.CASCADE,
                                            to='api.temperaturevalues')),
            ],
        ),
    ]
