# Generated by Django 4.0.5 on 2022-12-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='player',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
