# Generated by Django 4.0.5 on 2023-01-01 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_alter_gamelog_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
