# Generated by Django 4.0.5 on 2023-01-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerorder',
            old_name='player',
            new_name='user',
        ),
    ]
