# Generated by Django 4.0.5 on 2022-09-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_consumptionvalues_consumptionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('zoom_user_location', models.BooleanField()),
                ('username',
                 models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
