# Generated by Django 4.0.5 on 2022-09-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='zoom_user_location',
            new_name='zoomUserLocation',
        ),
    ]
