# Generated by Django 4.0.5 on 2023-01-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_player_playerorder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerorder',
            old_name='game_id',
            new_name='level_id',
        ),
    ]
