# Generated by Django 4.0.5 on 2023-01-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_rename_game_id_playerorder_level_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('level', models.ForeignKey(null=True,
                                            on_delete=django.db.models.deletion.SET_NULL,
                                            to='api.level')),
                ('log_entry', models.ForeignKey(null=True,
                                                on_delete=django.db.models.deletion.SET_NULL,
                                                to='api.gamelog')),
                ('user', models.ForeignKey(null=True,
                                           on_delete=django.db.models.deletion.SET_NULL,
                                           to='api.user')),
            ],
        ),
    ]
