# Generated by Django 4.0.5 on 2022-09-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_rename_zoom_user_location_user_zoomuserlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='tmp', max_length=200),
            preserve_default=False,
        ),
    ]
