# Generated by Django 4.0.5 on 2022-10-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('username', models.FloatField()),
                ('password_hash', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consumptionentry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='consumptionentry',
            name='value',
        ),
        migrations.DeleteModel(
            name='CSRF',
        ),
        migrations.RemoveField(
            model_name='location',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='PemKeys',
        ),
        migrations.RemoveField(
            model_name='portfoliocolouradapter',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='portfoliocolouradapter',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='temperatureentry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='temperatureentry',
            name='value',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='ColourHistory',
        ),
        migrations.DeleteModel(
            name='consumptionEntry',
        ),
        migrations.DeleteModel(
            name='consumptionValues',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioColourAdapter',
        ),
        migrations.DeleteModel(
            name='TemperatureEntry',
        ),
        migrations.DeleteModel(
            name='TemperatureValues',
        ),
    ]
