# Generated by Django 4.0.5 on 2022-10-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_users_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='access_token',
            field=models.TextField(null=True),
        ),
    ]
