# Generated by Django 4.0.5 on 2022-10-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_alter_users_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='game_role',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='currently_playing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
    ]
