# Generated by Django 4.0.5 on 2022-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_game_users_game_role_users_currently_playing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='currently_playing',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
