# Generated by Django 4.0.5 on 2022-10-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_remove_users_currently_playing_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='currently_playing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
    ]
