# Generated by Django 4.0.5 on 2022-10-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0017_playerorder_gamestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerorder',
            name='index_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerorder',
            name='index_won',
            field=models.IntegerField(null=True),
        ),
    ]
