# Generated by Django 4.0.5 on 2022-10-25 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0020_gamelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameState',
        ),
    ]
