# Generated by Django 4.0.5 on 2022-10-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_index_playerorder_join_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='performed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
