# Generated by Django 4.0.5 on 2022-10-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0024_tile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='performed',
            field=models.BooleanField(null=True),
        ),
    ]
