# Generated by Django 4.0.5 on 2022-11-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0025_alter_gamelog_performed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='performed',
            field=models.BooleanField(),
        ),
    ]
